id: PE7A7B1A2
initial_creation_type: ocr
source_metadata:
  volumes:
    fbdfaaaf54f44f319b134eebbe186e18:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་སྒོ་དྲུག་པའི་གཟུངས་ཀྱི་རྣམ་པར་བཤད་པ།
      total_pages: 1379
      volume_number: 37
